// Build assets/loops.js — a gitignored bundle of tempo-labelled drum loops as base64 data URIs.
// Embedding (rather than fetching) is what makes the loops work from a file:// origin, the same
// trick the preset banks already use. Source WAVs live in assets/loops/ and are gitignored too;
// re-run this after adding or replacing one.
//
// Usage: node make-loops.js
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const DIR = path.resolve(__dirname, '..', 'assets', 'loops');
const OUT = path.resolve(__dirname, '..', 'assets', 'loops.js');

const dur = (f) => parseFloat(execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', f]).toString().trim());

// BPM from the filename: the last integer in a musical range wins, so "loop 1 D sharp 130" -> 130.
function parseBpm(name) {
  const nums = (name.match(/\d+/g) || []).map(Number).filter(n => n >= 60 && n <= 220);
  return nums.length ? nums[nums.length - 1] : null;
}
function parseKey(name) {
  const m = /\b([A-G])\s*(sharp|#|flat|b)?\b/i.exec(name.replace(/\.[^.]+$/, ''));
  if (!m) return '';
  const acc = (m[2] || '').toLowerCase();
  return m[1].toUpperCase() + (acc.startsWith('s') || acc === '#' ? '#' : acc.startsWith('f') || acc === 'b' ? 'b' : '');
}

const loops = [];
for (const f of fs.readdirSync(DIR).filter(x => /\.mp3$/i.test(x)).sort()) {
  const base = f.replace(/\.mp3$/i, '');
  const bpm = parseBpm(base);
  if (!bpm) { console.warn('SKIP (no BPM in filename):', f); continue; }

  // Musical length comes from the WAV when present (MP3 duration carries encoder padding).
  const wav = path.join(DIR, base + '.wav');
  const srcDur = fs.existsSync(wav) ? dur(wav) : dur(path.join(DIR, f));
  const rawBeats = srcDur * bpm / 60;
  const beats = Math.round(rawBeats);
  const drift = Math.abs(rawBeats - beats);
  if (drift > 0.15) console.warn(`WARN ${f}: ${rawBeats.toFixed(3)} beats is not close to a whole number — is ${bpm} BPM right?`);

  // The loop length is DERIVED from tempo and beat count, never from the file duration: these files
  // carry ~18 ms of decay tail past the musical end, and looping the file length would drift.
  const loopSeconds = beats * 60 / bpm;
  const b64 = fs.readFileSync(path.join(DIR, f)).toString('base64');
  loops.push({
    id: base.replace(/[^\w]+/g, '-').toLowerCase(),
    name: base.replace(/[_-]+/g, ' ').trim(),
    bpm, beats, bars: beats / 4, key: parseKey(base),
    loopSeconds: +loopSeconds.toFixed(6),
    fileSeconds: +srcDur.toFixed(6),
    url: 'data:audio/mpeg;base64,' + b64,
  });
  console.log(`${f}: ${bpm} BPM · ${beats} beats (${beats / 4} bars) · loop ${loopSeconds.toFixed(4)}s · tail ${((srcDur - loopSeconds) * 1000).toFixed(1)}ms · ${(b64.length / 1024).toFixed(0)} KB b64`);
}

const body = 'window.OSCI_LOOPS=' + JSON.stringify(loops) + ';';
fs.writeFileSync(OUT, '/* GENERATED by tools/make-loops.js — gitignored. Tempo-labelled drum loops. */\n' + body + '\n');
console.log('\nwrote', OUT, (fs.statSync(OUT).size / 1024 / 1024).toFixed(2), 'MB,', loops.length, 'loops');
